### ISSUE TITLE
Full cds/amino acid sequence

### ISSUE THREAD

**Issue by jcsanchez2** [CroBiAd/DAWN#3]
Would be good to be able to retrieve the full cds and/or the amino acid sequence for a specific gene

**Comment by nathanhaigh** [comment]
I have added this plugin and modified it slightly to skip `exon` features. This is because the plugin falls back to some old/slow rendering code for features which overlap. Our GFF3 files will contain `cds` and `five_prime_UTR` and `three_prime_UTR` features which overlap with `exons`. Since we `cds` + `five_prime_UTR` + `three_prime_UTR` = `exons`, we can circumvent the feature overlap detection and dynamic UTR definition code entirely.

1. Right click gene model and select the "retrieve sequence" menu option:
![image](https://user-images.githubusercontent.com/2037575/42258448-fabd3d10-7f9a-11e8-9657-13f686b65af3.png)

2. Select your required transcript:
![image](https://user-images.githubusercontent.com/2037575/42258493-31a213be-7f9b-11e8-9440-c75fc37efd90.png)

3. Highlight, choose letter case or ahow/hide the transcript subfeatures together with upstream/downstream flanking sequence:
![image](https://user-images.githubusercontent.com/2037575/42259222-abd2f5ec-7f9e-11e8-907e-6d6da06aad2a.png)

4. Copy and paste the sequence from the window to wherever you need it.
